In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

print('Libraries imported successfully.')

Libraries imported successfully.

In [4]:
df1 = pd.read_csv(r"C:\Users\hp\Downloads\MENTOR SHIP\Fitness_Classes_Data\Fitness Classes Data\Classes April-May 2018.csv")

In [5]:
df1.head(10)

,ActivitySiteID,ActivityDescription,BookingEndDateTime (Month / Day / Year),BookingStartTime,MaxBookees,Number Booked,Price (INR)
0,HXP,20-20-20 2.45pm-3.45pm,08-Apr-18,14:45:00,25,12,499.0
1,HXP,20-20-20 2.45pm-3.45pm,15-Apr-18,14:45:00,25,15,499.0
2,HXP,20-20-20 2.45pm-3.45pm,22-Apr-18,14:45:00,25,14,499.0
3,HXP,20-20-20 2.45pm-3.45pm,29-Apr-18,14:45:00,25,9,499.0
4,HXP,20-20-20 2.45pm-3.45pm,06-May-18,14:45:00,25,7,499.0
5,HXP,20-20-20 2.45pm-3.45pm,13-May-18,14:45:00,25,10,499.0
6,HXP,20-20-20 2.45pm-3.45pm,20-May-18,14:45:00,25,7,499.0
7,HXP,20-20-20 2.45pm-3.45pm,27-May-18,14:45:00,25,3,499.0
8,TSC,20-20-20 7.00-8.00pm,04-Apr-18,19:00:00,24,10,499.0
9,TSC,20-20-20 7.00-8.00pm,11-Apr-18,19:00:00,24,12,499.0

In [8]:
df2 = pd.read_csv(r"C:\Users\hp\Downloads\MENTOR SHIP\Fitness_Classes_Data\Fitness Classes Data\Classes June 2018.csv")

In [9]:
df2.head(10)

,ActivitySiteID,ActivityDescription,BookingEndDateTime (Month / Day / Year),BookingStartTime,MaxBookees,Number Booked,Price (INR)
0,BRP,20:20:20 9.30-10.30am,01-Jun-18,9:30:00,35,28,499
1,BRP,20:20:20 9.30-10.30am,08-Jun-18,9:30:00,35,35,499
2,BRP,20:20:20 9.30-10.30am,15-Jun-18,9:30:00,35,31,499
3,BRP,20:20:20 9.30-10.30am,22-Jun-18,9:30:00,35,32,499
4,BRP,20:20:20 9.30-10.30am,29-Jun-18,9:30:00,35,19,499
5,BRP,20:20:20 10-11 Am,05-Jun-18,10:00:00,35,25,499
6,BRP,20:20:20 10-11 Am,12-Jun-18,10:00:00,35,23,499
7,BRP,20:20:20 10-11 Am,19-Jun-18,10:00:00,35,21,499
8,BRP,20:20:20 10-11 Am,26-Jun-18,10:00:00,35,18,499
9,BRP,20:20:20 10.00-11.00am,14-Jun-18,10:00:00,35,19,499

In [13]:
Cult = pd.concat([df1, df2],axis=0)

In [14]:
Cult.head(10)

,ActivitySiteID,ActivityDescription,BookingEndDateTime (Month / Day / Year),BookingStartTime,MaxBookees,Number Booked,Price (INR)
0,HXP,20-20-20 2.45pm-3.45pm,08-Apr-18,14:45:00,25,12,499.0
1,HXP,20-20-20 2.45pm-3.45pm,15-Apr-18,14:45:00,25,15,499.0
2,HXP,20-20-20 2.45pm-3.45pm,22-Apr-18,14:45:00,25,14,499.0
3,HXP,20-20-20 2.45pm-3.45pm,29-Apr-18,14:45:00,25,9,499.0
4,HXP,20-20-20 2.45pm-3.45pm,06-May-18,14:45:00,25,7,499.0
5,HXP,20-20-20 2.45pm-3.45pm,13-May-18,14:45:00,25,10,499.0
6,HXP,20-20-20 2.45pm-3.45pm,20-May-18,14:45:00,25,7,499.0
7,HXP,20-20-20 2.45pm-3.45pm,27-May-18,14:45:00,25,3,499.0
8,TSC,20-20-20 7.00-8.00pm,04-Apr-18,19:00:00,24,10,499.0
9,TSC,20-20-20 7.00-8.00pm,11-Apr-18,19:00:00,24,12,499.0

In [15]:
Cult.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3289 entries, 0 to 1111
Data columns (total 7 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   ActivitySiteID                           3289 non-null   object
 1   ActivityDescription                      3289 non-null   object
 2   BookingEndDateTime (Month / Day / Year)  3289 non-null   object
 3   BookingStartTime                         3289 non-null   object
 4   MaxBookees                               3289 non-null   int64
 5   Number Booked                            3289 non-null   int64
 6   Price (INR)                              3271 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 205.6+ KB

In [16]:
Cult.dtypes

ActivitySiteID                              object
ActivityDescription                         object
BookingEndDateTime (Month / Day / Year)     object
BookingStartTime                            object
MaxBookees                                   int64
Number Booked                                int64
Price (INR)                                float64
dtype: object

In [18]:
Cult.shape

(3289, 7)

In [19]:
Cult.columns

Index(['ActivitySiteID', 'ActivityDescription',
       'BookingEndDateTime (Month / Day / Year)', 'BookingStartTime',
       'MaxBookees', 'Number Booked', 'Price (INR)'],
      dtype='object')

In [20]:
Cult.rename(columns={'BookingEndDateTime (Month / Day / Year)':'BookingEndDateTime'},inplace=True)
Cult.rename(columns={'Number Booked':'Number_Booked'},inplace=True)
Cult.rename(columns={'Price (INR)':'Price'},inplace=True)
print('Rename successfully.')

Rename successfully.

In [21]:
Cult.columns

Index(['ActivitySiteID', 'ActivityDescription', 'BookingEndDateTime',
       'BookingStartTime', 'MaxBookees', 'Number_Booked', 'Price'],
      dtype='object')

In [22]:
Cult.isnull()

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
1107,False,False,False,False,False,False,False
1108,False,False,False,False,False,False,False
1109,False,False,False,False,False,False,False
1110,False,False,False,False,False,False,False
1111,False,False,False,False,False,False,False

In [23]:
Cult.isnull().sum()

ActivitySiteID          0
ActivityDescription     0
BookingEndDateTime      0
BookingStartTime        0
MaxBookees              0
Number_Booked           0
Price                  18
dtype: int64

In [24]:
Cult = Cult.loc[Cult['Price'].notna()]

In [25]:
Cult.isnull().sum()

ActivitySiteID         0
ActivityDescription    0
BookingEndDateTime     0
BookingStartTime       0
MaxBookees             0
Number_Booked          0
Price                  0
dtype: int64

In [27]:
Cult['BookingEndDateTime'] = pd.to_datetime(Cult['BookingEndDateTime'], format='%d-%b-%y')
Cult.head()

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,14:45:00,25,12,499.0
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,14:45:00,25,15,499.0
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,14:45:00,25,14,499.0
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,14:45:00,25,9,499.0
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,14:45:00,25,7,499.0

In [28]:
Cult['BookingEndMonth'] = Cult['BookingEndDateTime'].dt.month
Cult['BookingEndDay'] = Cult['BookingEndDateTime'].dt.day

In [29]:
Cult['BookingTime']=pd.to_datetime(Cult['BookingStartTime'],format="%H:%M:%S")

In [30]:
Cult['Booking_Start_Hour']=pd.to_datetime(Cult['BookingStartTime'],format="%H:%M:%S").dt.hour
Cult['Booking_Start_Min']=pd.to_datetime(Cult['BookingStartTime'],format="%H:%M:%S").dt.minute

Cult.head()

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price,BookingEndMonth,BookingEndDay,BookingTime,Booking_Start_Hour,Booking_Start_Min
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,14:45:00,25,12,499.0,4,8,1900-01-01 14:45:00,14,45
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,14:45:00,25,15,499.0,4,15,1900-01-01 14:45:00,14,45
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,14:45:00,25,14,499.0,4,22,1900-01-01 14:45:00,14,45
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,14:45:00,25,9,499.0,4,29,1900-01-01 14:45:00,14,45
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,14:45:00,25,7,499.0,5,6,1900-01-01 14:45:00,14,45

In [31]:
Cult.drop('BookingTime',axis=1,inplace=True)
Cult.head()

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price,BookingEndMonth,BookingEndDay,Booking_Start_Hour,Booking_Start_Min
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,14:45:00,25,12,499.0,4,8,14,45
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,14:45:00,25,15,499.0,4,15,14,45
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,14:45:00,25,14,499.0,4,22,14,45
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,14:45:00,25,9,499.0,4,29,14,45
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,14:45:00,25,7,499.0,5,6,14,45

In [32]:
print(Cult.duplicated().sum())

0

In [33]:
Cult['Activity'] = Cult['ActivityDescription'].str.rsplit(" ",n=1).str[0]
Cult['Activity_Time'] =Cult['ActivityDescription'].str.rsplit(" ",n=1).str[-1]
Cult.head()

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price,BookingEndMonth,BookingEndDay,Booking_Start_Hour,Booking_Start_Min,Activity,Activity_Time
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,14:45:00,25,12,499.0,4,8,14,45,20-20-20,2.45pm-3.45pm
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,14:45:00,25,15,499.0,4,15,14,45,20-20-20,2.45pm-3.45pm
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,14:45:00,25,14,499.0,4,22,14,45,20-20-20,2.45pm-3.45pm
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,14:45:00,25,9,499.0,4,29,14,45,20-20-20,2.45pm-3.45pm
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,14:45:00,25,7,499.0,5,6,14,45,20-20-20,2.45pm-3.45pm

In [34]:
Cult.isnull().sum()

ActivitySiteID         0
ActivityDescription    0
BookingEndDateTime     0
BookingStartTime       0
MaxBookees             0
Number_Booked          0
Price                  0
BookingEndMonth        0
BookingEndDay          0
Booking_Start_Hour     0
Booking_Start_Min      0
Activity               0
Activity_Time          0
dtype: int64

In [35]:
from datetime import datetime, timedelta
print('Libraries imported successfully.')

Libraries imported successfully.

In [36]:
def create_duration(time_str):
    start_time = datetime.strptime(time_str, '%H:%M:%S')
    end_time = start_time + timedelta(hours=1)
    return f"{start_time.strftime('%I:%M%p')} - {end_time.strftime('%I:%M%p')}"

In [37]:
Cult['Activity_Time'] = np.where(Cult.Activity_Time, Cult['BookingStartTime'].apply(create_duration),Cult.Activity_Time)

In [38]:
Cult.drop(columns=['ActivityDescription'],axis=1,inplace=True)
Cult.head()

,ActivitySiteID,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price,BookingEndMonth,BookingEndDay,Booking_Start_Hour,Booking_Start_Min,Activity,Activity_Time
0,HXP,2018-04-08,14:45:00,25,12,499.0,4,8,14,45,20-20-20,02:45PM - 03:45PM
1,HXP,2018-04-15,14:45:00,25,15,499.0,4,15,14,45,20-20-20,02:45PM - 03:45PM
2,HXP,2018-04-22,14:45:00,25,14,499.0,4,22,14,45,20-20-20,02:45PM - 03:45PM
3,HXP,2018-04-29,14:45:00,25,9,499.0,4,29,14,45,20-20-20,02:45PM - 03:45PM
4,HXP,2018-05-06,14:45:00,25,7,499.0,5,6,14,45,20-20-20,02:45PM - 03:45PM

In [39]:
# Function to calculate duration
def calculate_duration(time_range):
    time_range = time_range.replace(" ","")
    time_range = time_range.replace(".Am",'').replace('am',"").replace('AM',"").replace('am',"").replace('Am',"").replace('pm',"").replace('PM',"")
    time_range = time_range.replace('noon', '').replace("Noon","").replace(".",':')
    start_time_str, end_time_str = time_range.split('-')
    
    # Ensure times are in HH:MM format
    if ':' not in start_time_str:
        start_time_str += ':00'
    if ':' not in end_time_str:
        end_time_str += ':00'
    
    print(start_time_str, end_time_str)
    
    # Convert times to datetime objects
    start_time = datetime.strptime(start_time_str, '%H:%M')
    end_time = datetime.strptime(end_time_str, '%H:%M')
    
    if start_time.hour > end_time.hour:
        end_time = end_time.replace(hour=(end_time.hour + 12) % 24)
    
    # Calculate the duration in minutes
    duration = end_time - start_time
    duration_in_minutes = duration.total_seconds() / 60
    
    return duration_in_minutes

In [46]:
Cult['Activity_Duration'] = Cult['Activity_Time'].apply(calculate_duration)

02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
07:45 08:45
07:45 08:45
07:45 08:45
07:45 08:45
07:45 08:45
07:45 08:45
07:45 08:45
07:45 08:45
07:45 08:45
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
10:00 11:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
11:15 12:15
11:15 12:15
11:15 12:15
11:15 12:15
11:15 12:15
11:15 12:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
04:30 05:30
04:30 05:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
02:15 03:15
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
06:30 07:30
06:30 07:30
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
12:00 01:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
11:00 12:00
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:45 07:45
06:45 07:45
06:45 07:45
06:45 07:45
05:30 06:30
06:45 07:45
06:45 07:45
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:45 01:45
12:45 01:45
12:45 01:45
12:45 01:45
12:45 01:45
12:45 01:45
03:50 04:50
03:50 04:50
03:50 04:50
03:50 04:50
03:50 04:50
03:50 04:50
03:50 04:50
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
11:30 12:30
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
04:30 05:30
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
04:30 05:30
05:45 06:45
05:45 06:45
02:00 03:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
01:00 02:00
01:00 02:00
01:00 02:00
01:00 02:00
01:00 02:00
01:00 02:00
01:00 02:00
01:00 02:00
01:00 02:00
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
06:45 07:45
08:00 09:00
08:00 09:00
02:00 03:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:10 12:10
11:10 12:10
11:10 12:10
11:10 12:10
11:10 12:10
11:10 12:10
11:10 12:10
11:10 12:10
11:10 12:10
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
06:25 07:25
06:25 07:25
06:25 07:25
06:25 07:25
06:25 07:25
06:25 07:25
06:25 07:25
06:25 07:25
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
01:00 02:00
01:00 02:00
11:00 12:00
11:00 12:00
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
10:00 11:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
10:45 11:45
10:45 11:45
10:45 11:45
10:45 11:45
10:45 11:45
10:45 11:45
10:45 11:45
10:45 11:45
10:45 11:45
11:45 12:45
11:45 12:45
11:45 12:45
11:45 12:45
11:45 12:45
11:45 12:45
11:45 12:45
11:45 12:45
11:45 12:45
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
01:15 02:15
01:15 02:15
01:15 02:15
01:15 02:15
01:15 02:15
01:15 02:15
01:15 02:15
01:15 02:15
01:15 02:15
01:30 02:30
01:30 02:30
01:30 02:30
01:30 02:30
01:30 02:30
01:30 02:30
01:30 02:30
01:30 02:30
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
06:45 07:45
06:45 07:45
06:45 07:45
06:45 07:45
06:45 07:45
06:45 07:45
06:45 07:45
06:45 07:45
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:15 11:15
10:15 11:15
10:15 11:15
10:15 11:15
10:15 11:15
10:15 11:15
10:15 11:15
08:15 09:15
08:15 09:15
08:15 09:15
08:15 09:15
08:15 09:15
08:15 09:15
08:15 09:15
08:15 09:15
08:15 09:15
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
10:30 11:30
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:00 12:00
11:00 12:00
11:00 12:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00

In [41]:
Cult['Activity'] = Cult['Activity'].str.replace(' ', '', regex=False)

In [42]:
Cult['Activity'] = Cult['Activity'].str.rsplit(" ",n=1).str[0]

In [43]:
Cult['Activity'] = np.where(Cult['Activity'] == '20:20:20', 
                                   Cult['Activity'].str.replace(':', '-', regex=False), 
                                   Cult['Activity'])

In [44]:
Cult['Activity'] = np.where(Cult['Activity'] == 'Aquababies/tots', 
                                   Cult['Activity'].str.replace('Aquababies/tots', 'Aquatots&babies', regex=False), 
                                   Cult['Activity'])

In [45]:
Cult['Activity'] = np.where(Cult['Activity'] == 'Aquatots/baby', 
                                   Cult['Activity'].str.replace('Aquatots/baby', 'Aquatots&babies', regex=False), 
                                   Cult['Activity'])

In [47]:
Cult['Activity'] = np.where(Cult['Activity'] == 'Aquafit', 
                                   Cult['Activity'].str.replace('Aquafit', 'AquaFit', regex=False), 
                                   Cult['Activity'])

In [48]:
Cult['Activity'] = np.where(Cult['Activity'] == 'BLT', 
                                   Cult['Activity'].str.replace('BLT', 'BetterLivingTeam', regex=False), 
                                   Cult['Activity'])

In [50]:
Cult['Activity'] = np.where(Cult['Activity'] == 'Body', 
                                   Cult['Activity'].str.replace('Body', 'BodyAttack', regex=False), 
                                   Cult['Activity'])

In [52]:
Cult['Activity'] = np.where(Cult['Activity'] == 'BodyBalan', 
                                   Cult['Activity'].str.replace('BodyBalan', 'BodyBalance', regex=False), 
                                   Cult['Activity'])

In [53]:
Cult['Activity'] = np.where(Cult['Activity'] == 'Better', 
                                   Cult['Activity'].str.replace('Better', 'BetterLivingTeam', regex=False), 
                                   Cult['Activity'])
Cult['Activity'] = np.where(Cult['Activity'] == 'Conditioning', 
                                   Cult['Activity'].str.replace('Conditioning', 'BodyConditioning', regex=False), 
                                   Cult['Activity'])

In [54]:
Cult['Activity'] = np.where(Cult['Activity'] == 'BodyConditioningd', 
                                   Cult['Activity'].str.replace('BodyConditioningd', 'BodyConditioning', regex=False), 
                                   Cult['Activity'])

In [64]:
activity_map = {
    'BodyCondition10': 'BodyConditioning',
    'BodyCond3.50pm-': 'BodyConditioning',
    'Bodycondition': 'BodyConditioning',
    'Circuits7-7.45': 'Circuits'
}

Cult['Activity'] = Cult['Activity'].replace(activity_map)

In [63]:
activity_map = {
    'Circuits8.00-9.00pm': 'Circuits',
    'Fusion5pm': 'Fusion',
    'GentleKeepFit2': 'GentleKeepFit',
    'Gentlekeepfit': 'GentleKeepFit',
    'H.I.T.T6pm-': 'H.I.T.T',
    'H.I.I.T.': 'H.I.T.T',
    'HattonAbcBox': 'HattonABC',
    'HiitCircuit9.30-': 'HiitCircuit'
}

Cult['Activity'] = Cult['Activity'].replace(activity_map)

In [65]:
activity_map = {
    'JuniorGym11-12': 'JuniorGym',
    'JuniorGym4-5pm': 'JuniorGym',
    'JuniorGym10-11am': 'JuniorGym'
}

Cult['Activity'] = Cult['Activity'].replace(activity_map)

In [66]:
activity_map = {
    'LegBumTum': 'LegsBumsTums',
    'LegsBumsTum': 'LegsBumsTums',
    'LineDance': 'LineDancing',
    'LineDancing2pm': 'LineDancing'
}

Cult['Activity'] = Cult['Activity'].replace(activity_map)

In [72]:
activity_map = {
    'Pilates11.00-12.00': 'Pilates',
    'Pilates14:45-': 'Pilates'
}

Cult['Activity'] = Cult['Activity'].replace(activity_map)

In [73]:
activity_map = {
    'PureStretch11.00': 'PureStretch',
    'RockRollDancing3-': 'RockRollDancing'
}

Cult['Activity'] = Cult['Activity'].replace(activity_map)

In [75]:
activity_map = {
    'JnrGymInd': 'JunInduction',
    'Sh`Bam': 'Sha`Bam',
    'Step': 'StepAerobics',
    'Step': 'StepZumba',
    'Strength&stretch1230-1330': 'Strength&stretch',
    'Stretch': 'Strength&stretch',
    'Stretch6pm': 'Strength&stretch'
}

Cult['Activity'] = Cult['Activity'].replace(activity_map)

In [77]:
activity_map = {
    'Stroke': 'Strokeskills',
    'Strokeskills6': 'Strokeskills',
    'Strokeskills6pm-': 'Strokeskills',
    'Strokeskills7pm': 'Strokeskills',
    'StudioCyc1.10-': 'StudioCyc',
    'StudioCyc10.00': 'StudioCyc',
    'StudioCyc11.30-': 'StudioCyc',
    'StudioCycling7.05': 'StudioCyc'

}

Cult['Activity'] =Cult['Activity'].replace(activity_map)

In [79]:
activity_map = {
    'Swim': 'Swimfit',
    'Swimfit7am-': 'Swimfit',
    'Swimfit8pm-': 'Swimfit',
    'Swimfit6.30': 'Swimfit',
    'Swimfit6.30am': 'Swimfit',
    'Swimfit7pm-': 'Swimfit',
    'Tai-Chi12': 'TaiChi',
    'Zumba6.00-': 'Zumba',
    'BodyAttack9-10': 'BodyAttack',
    'Strokeskills7pm': 'Strokeskills',
    'StudioCyc9.05': 'StudioCyc',
    '5.30-6.30pmBody': 'BodyConditioning',
    'Combat': 'BodyCombat',
    'Zumba-': 'Zumba'
}

Cult['Activity'] = Cult['Activity'].replace(activity_map)

In [80]:
Cult.sort_values('BookingEndDateTime',ignore_index=True,inplace=True)